### ISSUE TITLE
Little Question...

### ISSUE THREAD

**Issue by nanoupi42** [spie-ics-ag/meraki2azure_ad#4]
Hi, 
I have deployed your app on docker.

On the documentation you said :
_Provide the parameters in exports.creds in config.js as instructed_
But I can't find the config.js where I have to set the parameters.

It's working with export command. I have to find a way to automate this export (if the container restart for example).

An other question the url to sign in is 
https://domain.com/auth/signin? 

because If I reach https://domain.com/auth/signin? the web page tell :

**You cannot initiate a login.
Please close this page and select the SSID WIFI.**

I don't understand the point of this behaviour ? Maybe a protection ? 

Thanks for your job and your share!

**Comment by lionelseydoux** [comment]
Hi,

Well spotted, the line "Provide the parameters in exports.creds in config.js as instructed" is deprecated. I'll remove it from the README.

All parameters are defined in the environment variables.
For docker, you can use a docker-compose file that will set the variables. This way, they'll always be set on restart.

You are right, the message "You cannot initiate a login" is not really clear. It's because some mandatory parameters are not set (like base_grant_url). In a real use-case, Meraki is redirecting to this webapp and thus passed a bunch of parameters (see https://developer.cisco.com/meraki/build/captive-portal-with-client-side-javascript/ ). In order to test it before the Meraki config is done, just pass a fake "base_grant_url" parameter. For example: https://domain.com/auth/signin?base_grant_url=whatever.  You'll get the proper Login page, be redirected to your Azure AD, which will redirect you to the fake base_grant_url after a successful login... there will be an error message, but if you go again to https://domain.com/ you'll be signed in.

I hope is helps. Thank you for your interest in this project.
